print("="*40)
print("Programming", "Essential", "in", sep="***", end="...")
print("Python",)
print("="*40)
print("     *", "   *   *", " *       *", "***     ***", "   *   *", "   *   *", "   *   *", "   *****", sep="\n")
print("="*40)
print("I'm student", "\n")
print("="*40)
print("\"I'm\"", "\"\"learning\"\"", "\"\"\"python\"\"\"", sep="\n")
print("="*40)
result = 500 * (10 ** 8)
print(result)
print("="*40)
result = 777 * (10 ** 16)
print(result)
print("="*40)

